"""
Alert model module - defines the data structure for security alerts
with serialization and severity classification capabilities.
"""

from dataclasses import dataclass, asdict
from datetime import datetime
from enum import Enum
from typing import Dict, Any, Optional
import json


class AlertSeverity(Enum):
    """Alert severity levels"""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlertType(Enum):
    """Alert type categories"""

    PORT_SCAN = "port_scan"
    BRUTE_FORCE = "brute_force"
    DOS = "dos"
    WEB_ATTACK = "web_attack"
    DNS_EXFILTRATION = "dns_exfiltration"
    SIGNATURE_MATCH = "signature_match"
    BEHAVIORAL_ANOMALY = "behavioral_anomaly"


@dataclass
class Alert:
    """
    Represents a security alert generated by the IDS.

    Attributes:
        rule_id: Unique rule identifier (e.g., 'SIG-001')
        name: Human-readable alert name
        alert_type: Type of threat detected
        severity: Severity level
        source_ip: Source IP address
        dest_ip: Destination IP address
        source_port: Source port (optional)
        dest_port: Destination port (optional)
        protocol: Network protocol
        message: Detailed description
        timestamp: When the alert was generated
        raw_packet: Raw packet data (optional, for forensics)
        confidence: Confidence score (0.0 to 1.0)
    """

    rule_id: str
    name: str
    alert_type: AlertType
    severity: AlertSeverity
    source_ip: str
    dest_ip: str
    source_port: Optional[int]
    dest_port: Optional[int]
    protocol: str
    message: str
    timestamp: datetime
    raw_packet: Optional[str] = None
    confidence: float = 1.0
    packet_id: Optional[int] = None

    def to_dict(self):
        d = {
            "id": getattr(self, "id", None) or getattr(self, "alert_id", None) or getattr(self, "_id", None),
            "source_ip": getattr(self, "source_ip", None) or getattr(self, "src_ip", None) or self.source_ip,
            "dest_ip": getattr(self, "dest_ip", None) or getattr(self, "dst_ip", None) or self.dest_ip,
            "protocol": getattr(self, "protocol", None) or self.protocol,
            "alert_type": (self.alert_type.value if hasattr(self.alert_type, "value") else str(self.alert_type)),
            "severity": (self.severity.value if hasattr(self.severity, "value") else str(self.severity)),
            "name": getattr(self, "name", None),
            "message": getattr(self, "message", None),
            "payload": getattr(self, "payload", None),
            "timestamp": (
                self.timestamp
                if isinstance(getattr(self, "timestamp", None), str)
                else getattr(self, "timestamp", datetime.now()).isoformat()
            ),
        }
        if getattr(self, "packet_id", None) is not None:
            d["packet_id"] = self.packet_id
        if getattr(self, "raw_packet", None) is not None:
            d["raw_packet"] = self.raw_packet
        return d

    def to_json(self) -> str:
        """Serialize alert to JSON string."""
        return json.dumps(self.to_dict(), indent=2)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Alert":
        """Create Alert instance from dictionary."""
        data["timestamp"] = datetime.fromisoformat(data["timestamp"])
        data["alert_type"] = AlertType(data["alert_type"])
        data["severity"] = AlertSeverity(data["severity"])
        return cls(**data)

    def __str__(self) -> str:
        """String representation for console output."""
        return (
            f"[{self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}] "
            f"{self.severity.value.upper()} - {self.name} "
            f"({self.alert_type.value}) - "
            f"Src: {self.source_ip}:{self.source_port or '*'} -> "
            f"Dst: {self.dest_ip}:{self.dest_port or '*'} "
            f"[Confidence: {self.confidence:.2f}]"
        )
